#!/bin/sh
# nfsmount calls this script when mounting a filesystem with locking
# enabled, but when statd does not seem to be running (based on
# /var/run/rpc.statd.pid).
# It should run statd with whatever flags are apropriate for this
# site.
PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# Read config
DEFAULTFILE=/etc/default/nfs-common
NEED_IDMAPD=
if [ -f $DEFAULTFILE ]; then
    . $DEFAULTFILE
fi

# First try systemd if it's installed.
if [ -d /run/systemd/system ]; then
    # Quit only if the call worked.
    systemctl start nfs-statd.service && exit
fi

# Fall back to launching it ourselves.
exec rpc.statd --no-notify $STATDOPTS
